version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: mysql-gastos
    restart: always
    environment:
      MYSQL_DATABASE: gastos_db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root

volumes:
  db_data:

